# Generated by Django 5.2.6 on 2025-09-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ball', 'Football'), ('jersey', 'Jersey'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('equipment', 'Equipment')], default='accessory', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
