# Generated by Django 5.2.6 on 2025-09-17 00:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ball', 'Football'), ('jersey', 'Jersey'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('equipment', 'Equipment')], default='accessory', max_length=20)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
